project:
  type: website
  output-dir: docs

website:
  title: "JU-F22-MSDSSB-DSOC-02"
  navbar:
    left:
      - file: index.qmd
        text: Syllabus
      - late.qmd
      
  sidebar: 
    - title: Homework
      style: "docked"
      background: light
      contents:
        - hw-instructions/hw-01-instr.qmd
        - hw-instructions/hw-02-instr.qmd
        - hw-instructions/hw-02-py-instruction.qmd
        - hw-instructions/hw-03-instr.qmd
        - hw-instructions/hw-03-py-instruction.qmd
        - hw-instructions/hw-04-instr.qmd
        - hw-instructions/hw-05-instr.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: true



