---
title: "Data Science Concepts / Tools"
---

::: callout-important
## Information for late coming students

Welcome! You are in the right place to get into the course. There is a lot of material. Here we provide a [checklist for late coming students](https://janlorenz.github.io/JU-F22-MSDSSB-DSOC-02/late.html)
:::


::: callout-note
This is a developing syllabus! It will be continuously updated and your main entrance to course material. 
:::

# Basic Information 

## Modules Data Science Concepts / Methods

These two modules are orchestrated in close cooperation

* Data Science Concepts (Core module: MSDSSB-DSOC-02)
* Data Science Tools (Methods module: MDSSB-MET-01)

You should know how the courses are integrated in the overall [Master program](https://www.jacobs-university.de/study/graduate/programs/data-science-society-and-business) and the module descriptions from the [DSSB Handbook](  https://www.jacobs-university.de/sites/default/files/dssb_master_handbook_2021.pdf). 

## Courses and Instructors

Thursday is the concepts and tools day!

**Data Science Tools in R:**	Thursday 9:45 - 11:00	[Armin Müller](https://www.jacobs-university.de/directory/armm%C3%BCller)   
**Data Science Tools in Python:** Thursday 11:15 - 12:30	[Martin Gestefeld](https://www.jacobs-university.de/directory/gestefeld)  
**Data Science Concepts Lectures:** Thursday 14:15 - 17:00 (2 Sessions) [Jan Lorenz](http://janlo.de)

## Goal 

Our goal in the two modules is to enable you to

* create and maintain a digital working environment on your computer to do data science
* learn core concepts in data science, that means
  * learn concepts to explore data (visualize, import, wrangle)
  * learn or refresh some *mathematics* and *statistics* concepts through the data science lens
  * learn concepts to model and draw conclusions from data (model, infer, predict)
* learn to program in the data science languages R and python, and become able to learn new skills in these independently
* do a data science project of your own interest

You can build a good basis for your more and more independent work in the whole program. 


## Expectations for students

We rely on your **engagement**. Taken holistically, engagement is many-faceted and includes

* Preparation (looking at readings and material before class, being informed about syllabus and course material)
* Focus (avoid distraction during in class and online activities)
* Presence (listening and responding during group activities)
* Asking questions (in class, out of class, online, offline)
* Specificity (being specific when referring to ideas from readings and discussions)
* Synthesizing (making connections between concepts from reading and discussion)

(Adapted from [Twitter: Mark Sample](https://twitter.com/samplereality/status/1564016056208949249?s=20&t=QZziUqevEXCWeO5MBAHiIQ))

## Online Infrastructure

[**Campusnet**](https://campusnet.jacobs-university.de)
This is the official registration site. Besides the final grade input for the modules we will *not use it* in the courses, but you should be able to get back to this site from there once you are lost. 

[**jMoodle**](https://elearning.jacobs-university.de) 
An e-learning platform provided by Jacobs University. Log in with your campusnet credentials. 
Under the Data Science Concepts Course (identifier MDSSB-DSOC-02_f2022_1) we publish information (e.g. survey links) which shall be shared only among participants of the course. (After all this is a public website, although it is not intended to be announced publicly.)

::: callout-important
Test to log in and visit the *Data Science Concepts* course on [*jMoodle*](https://elearning.jacobs-university.de). **Be prepared to go there during class!**
:::

**Microsoft Teams:** In MS Teams there is a Team for the course. Teams will be used for hybrid online and in class teaching. It is expected that you come to class in presence if possible. Participation should only be online when abroad or CoViD-isolated at home. The "General" channel can be used for announcements. You can also post there. You can also post to me directly over Teams and hope for a quick answer.

If possible, **recordings** are made via Teams and saved in the Teams general channel under Files -> Recordings. 

**GitHub:** All delivery and submission of homework and the final exam is via individual repositories on Github in the GitHub organization <https://github.com/JU-F22-MDSSB-MET-01>. Details are in the lecture [slides of week 1](https://docs.google.com/presentation/d/1GyEClkRDo5aOKuHeOZxgvz2uqo_x5t-c1CQ-ksGXTq0/edit?usp=sharing) and [Homework 01](hw-instructions/hw-01-instr.qmd) on this page.  

## Software

We use a mandatory set of software. Details are in the [slides of week 1](https://docs.google.com/presentation/d/1GyEClkRDo5aOKuHeOZxgvz2uqo_x5t-c1CQ-ksGXTq0/edit?usp=sharring). Our task with highest priority is to realize that everyone has full installation and functionality on their local machines. All software is freely available.

## Assessment and Grading

### Data Science Concepts Module

Assessment is based on an exam of 120 minutes. It is scheduled officially on [campusnet](https://campusnet.jacobs-university.de) by academic offices for **Dec 15, 12:30-14:30**. 

The exam will be open-book and take-home exam. It will be delivered individually via GitHub through the organization <https://github.com/JU-F22-MDSSB-MET-01> as the Homework. 

### Data Science Tools Module

Assessment is based on a **team project** (see below) of approximately 4000-5000 words. Which are delivered in personalized repositories in the GitHub organization <https://github.com/JU-F22-MDSSB-MET-01>.

Additionally, the handbook lists a *requirement* to pass the module and a *bonus* option to increase the grade by 0.33 (while the best grade is also possible with a great project report without the bonus). 

- **Requirement:**  Half of the homework assignment tasks need to be correctly solved. These do not determine the grade. We will check this after the deadline for the last homework passed at the end of classes. 
- **Bonus:** The individual repositories about Corona **hw-ind-corona-USERNAME** and the ESS **hw-ind-ess-USERNAME** shall be cleaned from not necessary files. All analysis the qmd-Document should be complete and the questions should be answered in a consistent way. The rendered html document should look well formatted and should be readable as a report independent from the instructions. 


### Data Science Tools Project Report 

The project report is the graded assessment of the Tools module. 

Important information on the preparation of the Data Science Project Reports is in the Presentation for [Week 11](W11_projects.qmd). Please go through this.

Advice on the structure (Executive Summary, Introduction, Data, Analysis, Conclusion) is in the template you have in your repository. 

Advice: 

- Find a manageable dataset: at least 50 cases, good is 10-20 variables with a mix of categorical and numeric. Deviations are allowed based on your interest and capability. 
- Go through the visualizations, statistics, and models we had in lectures and homework and think if similar things would be interesting.
- The goal is **not an exhaustive data analysis**. Do not calculate every statistic and procedure you have learned for every variable, but rather **show that you can ask meaningful questions** and answer them with results of data analysis and proficient interpretation and presentation of the results.
- Do NOT blindly do all visualization and all statistic on all variables in the data set! You do that in your data exploration but that should not go into your report as is. At some point you have to focus on what is needed to answer your questions. Your report is not a documentation of all your steps. Throw out what is not needed anymore, improve the remaining visualizations, and explain well in the text what you want to communicate.  
- A single high quality visualization which shows a point clearly will receive a much higher appreciation than a large number of poor quality visualizations without an explanation what they should communicate.







# Learning Resources

## Core resources

A large part of the course will build on or be inspired by material in **Data Science in the Box** <https://datasciencebox.org/> by Mine Çetinkaya-Rundel and the data science education community around. 
You can also use the website for accompanying self-study on selected topics. 

A core resource for self-learning data science with R is **R for Data Science** <https://r4ds.had.co.nz/> by Hadley Wickham and the R data science community around. This is a valuable resource for self-studying particular topics using `tidyverse` tools. 
Just out: **Tidy Modeling with R** <https://www.tmwr.org/> by Max Kuhn and Julia Silge on using `tidymodels`. 

A core resource for data science basics with python is the **Python Data Science Handbook** <https://jakevdp.github.io/PythonDataScienceHandbook/> by Jake VanderPlas. Also there is a good video playlist <https://www.youtube.com/playlist?list=PLWKjhJtqVAbkmRvnFmOd4KhDdlK1oIq23> and a 4-hour "full-course" video <https://youtu.be/rfscVS0vtbw>.

## Mathematics

Some helpful YouTube videos for those recaping maths:

How to read math https://www.youtube.com/watch?v=Kp2bYWRQylk

## Data Visualization

*ggplot2: Elegant Graphics for Data Analysis* <https://ggplot2-book.org> is a resource on understanding the logic of ggplot better. 

Websites on how to decide for what visualization to choose:   
<https://www.data-to-viz.com/>   
<https://datavizcatalogue.com/search.html>



*The number of freely available learning resources is increasing rapidly.* 

*Everyone has a different learning style and a different background. Thus, different material may be most helpful.*

*This list shall be extended. Good self-study resources for data science with python, mathematics, statistics, data visualization, etc. shall be added here. Contact me if you find something useful to share. Ideally, with a short description when it may be most helpful.*

# Course Material and Schedule

## Week 1, Sep 1: What is Data Science? Course organization, toolkit {-}

[Slides Week 1](https://docs.google.com/presentation/d/1GyEClkRDo5aOKuHeOZxgvz2uqo_x5t-c1CQ-ksGXTq0/edit?usp=sharring)

Find the homework assignment "Homework 01" on this website. Deadline: Sunday, Sep 18. The content will be discussed in the Tools course in Week 2 and 3



## Week 2, Sep 8: No lectures {-}

**There will be no lectures, because of a mandatory central events!**   
The first Data Science Tools courses in the morning will take place!

Reading instead of lecture:
[R for Data Science: Chapter 3 on Data Visualization](https://r4ds.had.co.nz/data-visualisation.html)


## Week 3, Sep 15: Data visualization, Data formats {-}

[Slides Week 3](https://docs.google.com/presentation/d/12K3c6nwiBcEM84pVfqBjlQ8J3o3x2CkxDf2Jmyz-0z0/edit?usp=sharing)

Lab work on code. Clone from: <https://github.com/JU-F22-MDSSB-MET-01/codebase-janlorenz.git>
In RStudio, work through

- 2022-09-15_ggplot_and_pipe.R
- 2022-09-15_profiles.qmd

## Week 4, Sep 22: Data import, data Wrangling {-}

[Slides Week 4](W4.qmd)  
Download instructions: <https://quarto.org/docs/presentations/revealjs/presenting.html#print-to-pdf>

Including some recap of the toolkit.    
Questions and advice on Homework 02 (mostly in Recording).  


## Week 5, Sep 29:  More under the hood, Relational Data, Exploratory Data Analysis {-}

[Slides Week 5](W5.qmd)  
Download instructions: <https://quarto.org/docs/presentations/revealjs/presenting.html#print-to-pdf>

Topics: 

- More under the hood
- Augmented vectors: Factors and Dates
- Strings
- Relational Data: Joins, joins, joins ...
- Math: Sets and vectors
- Exploratory Data Analysis
- Data Science Projects

**Homework 02 due next Sunday.**   
**Homework 03 comes over the weekend.**

## Week 6, Oct 6:  Functions, Logarithms and Exponentials, Modeling, Fitting a Linear Model {-}

[Slides Week 6](W6.qmd)  
Download instructions: <https://quarto.org/docs/presentations/revealjs/presenting.html#print-to-pdf>

**Homework 03 is due Oct 16.**


## Week 7, Oct 13: Descriptive statistics, Wisdom of Crowds, Calculus, Epidemic Models {-}

[Slides Week 7](W7.qmd)  
Download instructions: <https://quarto.org/docs/presentations/revealjs/presenting.html#print-to-pdf>

**Homework 03 is due Oct 16.**

## Week 8, Oct 20: Homework topics: Typical Data Issues, More Linear Models and Interpretation {-}

Topics: 

- Errors, Differences, Missings in Data
- More Linear Models
  - More predictors
  - Main effects and interaction effects
- *To be finished*

[Slides Week 8](W8.qmd)  
Download instructions: <https://quarto.org/docs/presentations/revealjs/presenting.html#print-to-pdf>

**Homework 04 should come. Due Nov 6.**

## Week 9, Oct 27: Classification Problems, Logistic Regression, Prediction {-}

[Slides Week 9](W9.qmd)  
Download instructions: <https://quarto.org/docs/presentations/revealjs/presenting.html#print-to-pdf>

**Homework 04 due in 10 days.**

## Week 10, Nov 3: Performance Metrics, Cross validation, Hypothesis testing, Math: Probability {-}

[Slides Week 10](W10.qmd)  
Download instructions: <https://quarto.org/docs/presentations/revealjs/presenting.html#print-to-pdf>

**Homework 04 due in 3 days**  
**Homework 05 should come. Due Nov 20.**

## Week 11, Nov 10: Data Analysis Projects, Collaborative Git {-}


[Slides Week 11 Projects](W11_projects.qmd)  
[These slides are a main reference for your data science project.]{style='color:red;'}  

Download instructions: <https://quarto.org/docs/presentations/revealjs/presenting.html#print-to-pdf>

## Week 12, Nov 17: Probability, Principal Component Analysis  {-}

[Slides Week 12](W12.qmd)

**Homework 05 due in 3 days**  

## Week 13, Nov 24:  Probability distributions, Cluster Analysis {-}

[Slides Week 13](W13.qmd)

## Week 14, Dec 1: Course Review, Exam preparation {-}

**Homework 06 should come before Thursday. It includes questions similar to what will be asked in the exam of "Data Science Concepts". We can discuss it in class.**

**The deadline of Homework 06 will be the end of the semester. However, it obviously makes sense to do it before the exam. **

## Last *Data Science Tools* Sessions, Dec 8 {-}

9:45 - 12:30 in the regular rooms. 

**Informal project presentations**

- Each project team presents their report and the main insights. 
- There is no need to prepare additional slides, we can look at the visualization on the html-page of the report. 
- Each presentation should be 5-15 minutes, and allow for short questions or feedback. 
- The presentation is not graded. 
- The final version of the report can be improved afterwards. 

**Deadline for the reports is the end of the year Dec, 31. We (the instructors) need to submit the grades by January 9, 2023.**


## Exam *Data Science Concepts* module, Dec 15 {-}

Scheduled officially on [campusnet](https://campusnet.jacobs-university.de) by academic offices.



<!-- 
Next things: Data Science Box: Scientific studies and confounding, ends with conditional probability and independence



-->
