---
title: "Homework 03"
subtitle: ""
---

```{r include = FALSE}
library(tidyverse)
```

The goal of this assignment is to do steps of exploratory data analysis (EDA) with the data about corona and the European Social Survey (ESS) from [Homework 02](hw-02-instr.qmd). 

## Corona

Continue to work on your repository **corona-ind-USERNAME** and make the analysis in R-chunks. 

Create a new Quarto-document and save it as "Corona_Analysis.qmd". 

- Customize the YAML with the title "Corona Analysis", your name, and output format being a standalone html-file with embedded resources. Enable code-folding in the output html file. 
- Write a chunk labeled `data` where you load the `tidyverse` library and import the data from *Our World in Data* (OWiD) into a tibble `owid` and the data from the *World Health Organization* (WHO) into a tibble called `who` (use `read_csv` for both). 
- Document what you did: Write a headline `## Data` before the chunk `data` and briefly describe the two data sources and link the data files. 

:::{.callout-tip}
- In <https://github.com/JU-F22-MDSSB-MET-01/corona-ind-janlorenz/blob/main/Download_corona_data.R> you find a script which downloads the corona datasets from OWiD and WHO. You can copy this. 
- In <https://github.com/JU-F22-MDSSB-MET-01/corona-ind-janlorenz/blob/main/Corona.qmd> you find an example for the YAML and the data import chunk. 
:::

### **Question 1:** Is the data of OWiD and WHO the same?

Write a new headline `## Differences between OWiD and WHO data`, make the following analysis in a chunk, and write an answer to the question. Guide for the analysis:

- Create a joined tibble. This can be done with a chain of pipes `|>`. 
  - Make a new tibble `who_owid` where you left join `owid` to `who`. Use the combination of the data and the country as the key. To that end you have to identify the corresponding columns in `who` and `owid` with the named vector  `c("Date_reported" = "date", "Country" = "location")`. 
  - Use `select` to select and rename columns in `who_owid` such that you have columns for `Date`, `Country`, `New_cases_who`, `New_cases_owid`, `Total_cases_who`, and `Total_cases_owid`. 
- Make a visualization where the new cases in WHO and OWiD appear as two lines. Filter for the time before 2020-07-01 and four countries: Germany, France, India, and a country of your choice (Hint: use `%in%`). Then facet your visualization by country.
- Repeat the visualization for the comparison of WHO and OWiD data for the total cases. 
- Below the visualizations, explain what is visualizaed and then answer the question based on the visualizations. (Some guiding questions: What are the differences? How severe are the differences on a daily basis and in the long run? What data shows more fluctuations?) Bonus: What is the reason for the difference?  

:::{.calloUt-tip}
For comparing `New_cases_who` and `New_cases_owid` you need a to make the tibble longer (`pivot_longer`) such that you have one column with a categroical variable specifying the data source and one column with the actual value of the new cases in each data set. Then you can make a ggplot with `geom_line` where you make two lines by assigning the data source to the color aesthetic. 

For faceting, use `facet_wrap`. It is useful to specify that there should be only one column and that scales are specified such that each facet has its own y-axis scale (called `free_y`). 

The same advice holds for the visualization of total cases. 
:::

### **Question 2:** Are there patterns in the timeline of new cases which seem unrelated to the potential spread of the virus in the population? How could we smooth them best? 

Write a new headline `## Smoothing new cases`, make a chunk where you compute three additional columns with smoothed case numbers (see below), make a visualization and explain which is most appropriate to use and why. 

- Computed a new tibble `who_smoothed` from `who` for this question. (There would be no essential difference with `owid`.) For each day compute the average of the actual day and some days directly before such that each new value is an average of 3, 7, or 10 days. Call the three new columns `New_cases_smooth3`, `New_cases_smooth7`, and `New_cases_smooth10`. The *average* is the sum of all values divided by the total number of days. Use `mutate`. For each column use `lag` several times for each previous day (see `?lag`). Don't forget to group by countries!
- Visualize the timeline for Germany using a time span between 6 and 12 month. Make one panel for `New_cases_smooth3`, `New_cases_smooth7`, and `New_cases_smooth10` respectively. (Hint: Either use `pivot_longer` and faceting, or three ggplot objects combined using the package `patchwork`.)
- Answer the question. What is the pattern which seems unrelated to the spread of the virus? Which is the most appropriate smoothing, 3, 7, or 10 days and why?

### **Question 3:** How do deaths follow cases?

Make a new headline about this question in your report.

In `owid`, there are variables `new_cases_smoothed` and `new_deaths_smoothed` which you can use for convenience to explore this question. 

To explore the connection between COVID-19 cases and deaths focus on the first wave in Germany. In `owid`, filter the data for Germany and dates before 2020-07-01. Plot `new_cases_smoothed` and `new_deaths_smoothed` in one line plot using color to distinguish both. (Hint: Use `pivot_longer`.) Now, produce a new variable `scaled_lagged_cases` where you do a shift-and-scale transformation of `new_cases_smoothed`: That means you scale down
the number of cases by multiplying a factor $y$(< 1) and you `lag` the number of cases along the time
axis by $x$ days using `y * lag(new_cases_smoothed, x)`. 

- Play with numerical values of $x$ and $y$ by plotting `scaled_lagged_cases` together with `new_death_smoothed`. Find values for such that both lines overlap as good as possible. Put this visualization into the report. 
- Describe what these "visually calibrated" values of $x$ and $y$ tell us about the relation of cases and deaths of  COVID-19? 
- Redo the line plot with your calibrated values for all dates in Germany. Describe how the connection
between new cases and deaths changes in the course of the pandemic. List potential reasons. 
- Repeat this analysis for another country of your choice. To that end find out the time range of the first wave
in the country before. Do you get the same $x$ and $y$ by visually calibrating for this country?

### **Question 4:** How is the severity of the corona pandemic in countries related to human development? 

Make a new headline about this question in your report. 

Human development is meant to be measured by the human development index of the United Nations Development Programme.
Briefly, describe in the report how the Human Development Index (HDI) is composed. 

Use `owid`. Make a figure which visualizes each country as a point with `human_development_index` on the horizontal and  `total_deaths_per_million` on the vertical axis. Filter the values for the date 2022-08-31. Filter out all rows which do not represent countries. (Hint: You can take all rows which have a valid value for `continent`.) Make the size of dots such that the area is proportional to the `population`. (Hint: Use the `scale_size_area()` as an additional layer.) Color the dots by `continent`. 

Describe the visible relation of HDI and total corona related deaths per million. Emphasize what you find interesting, and hypothesize about potential reasons for the finding. 

### Submit your report

Make sure that your rendered html file reads nicely as a report. Polish the formatting if necessary. 
Commit your qmd-file and the rendered html-file and push it to GitHub. 



## European Social Survey

Continue to work on your repository **ess-ind-USERNAME** and make the analysis in python-chunks. 
**You have to look ESS Data Documentation <https://ess-search.nsd.no/>.**


1. Create a new Quarto-document and save it as "ESS-analysis.qmd" (alternatively as "ESS-analysis.ipynb" if you can render html-files similarly from it).

- Customize the YAML with the title "European Social Survey Analysis", your name, and output format being a standalone html-file with embedded resources. Enable code-folding in the output html file. 
- Write a chunk labeled `data` where you load the `tidyverse` library and import the dataset you downloaded for Homework 02.  
- Document what you did: Write a headline `## Data` before the chunk `data` and briefly describe the data source. 
- For each of the following questions write a fitting headline to structure your report.


### **Question 1:** What is the ranking of European countries with respect to of average satisfaction with life? 

- Compute the average of `stflife` for each country-year combination. Make a table with four columns: the country name and the average life satisfaction for the years 2006, 2012, and 2018. Order the table by the values in 2018 and print it nicely in your report.  
To that end, you must create new variables `countryname` from the two-character ISO-codes in `cntyr` (use the library `pycountry`) and a new variable `year`.   
**Beware:** The ESS variables have coded missing values as large numbers like 77 or 88. Find out these values and recode them as `NA` before computing averages!  
- Describe what you find remarkable in the table. (Who is on top? who at the bottom? Any interesting trends? Any geographical patterns?) 


### **Question 2:**  What is the relation of the emotional attachment of Europeans to their own country and to Europe? 

Emotional attachment to Europe may diminish emotional attachment to the country. Test if this is true with the variables `atchctr` and `atcherp`. 
First, look up the wording of the two questions and the answering options and write it into the report. 

Build two visualizations and put them in the report. **Beware:** First recode the missing values as `NA`! (See above.)

a. A visualization where you first count the number of individuals each combination of valid values of `atchctr` and `atcherp`. Then plot each combination as a dot with `atchctr` on the x-axis, `atcherp` on the y-axis, and the number of individuals represented by size and color and color of the dot. 
b. Make a lowess (locally weighted scatterplot smoothing) line of `atchctr` on the x-axis, `atcherp` on the y-axis using the function `regplot` from `seaborn`. 

Answer the question based on the visualization. 


### **Question 3:**  What is the relation of the emotional attachment to the own country and the opinion about further of European integration? 

This is analog to Question 2 with `euftf` instead of `atcherp`. 
First, look up the wording of `euftf` and the answering options and write it into the report. 
Beware: First recode the missing values as `NA`! (See above.)

Build two visualizations as above.  

Answer the question. 

### **Question 4:** How many observations are there for each country-year combination? 

Compute the numbers and list them nicely in a table in your report. 

Are the numbers roughly proportional to the population in these countries? Discuss if the answer creates some shortcomings about the answers to Questions 2 and 3. How could these be mitigated?


### **Question 5:** Answer your own exploratory question

Look up questions behind the variables in the ESS data set, formulate a question, and answer it with summarizing, and  visualization.